param(
    [string]$Godot = 'godot',
    [string]$Python = 'python',
    [switch]$ExportWeb
)
$ErrorActionPreference = 'Stop'
$taskRoot = Split-Path $PSScriptRoot -Parent
$taskPreviousDirectory = Get-Location
$taskPreviousAppData = $env:APPDATA
try {
    Set-Location -LiteralPath $taskRoot
    if (-not (Get-Command $Godot -ErrorAction SilentlyContinue)) {
        $taskBundledGodot = Join-Path $env:LOCALAPPDATA 'Programs\Godot\Godot_v4.7.2-stable_win64_console.exe'
        if (-not (Test-Path -LiteralPath $taskBundledGodot)) {
            throw "Godot command '$Godot' was not found. Supply -Godot with a Godot 4.7.2 console executable."
        }
        $Godot = $taskBundledGodot
    }
    # Godot 4.7.2 rewrites the tracked import sidecars with Windows line endings
    # during a headless editor pass. Keep pre-existing developer edits intact,
    # while discarding only those generated by this disposable audit import.
    $taskOriginalImports = @(& git diff --name-only -- '*.import')
    New-Item -ItemType Directory -Force -Path '.audit/logs', '.audit/userdata', '.audit/web' | Out-Null
    Set-Content -LiteralPath '.audit/.gdignore' -Value ''
    $taskVersion = & $Godot --version
    if ($LASTEXITCODE -ne 0 -or $taskVersion -notmatch '^4\.7\.2\.stable') {
        throw "Expected Godot 4.7.2 stable; got $taskVersion"
    }
    Write-Output $taskVersion
    # Both GameMan.new_game and the original smoke scene write saves. Redirect
    # the entire Godot application-data root, including Jukebox's audio settings.
    $env:APPDATA = (Resolve-Path '.audit/userdata').Path
    foreach ($taskCase in @(
        @{Name='import'; Args=@('--headless','--path','.','--editor','--quit')},
        @{Name='startup'; Args=@('--headless','--path','.','--quit-after','90')},
        @{Name='smoke'; Args=@('--headless','--path','.','tests/smoke.tscn')},
        @{Name='redesign'; Args=@('--headless','--path','.','tests/redesign.tscn')},
        @{Name='audit-probe'; Args=@('--headless','--path','.','tests/audit_probe.tscn')}
    )) {
        $taskArguments = $taskCase.Args
        $taskLog = Join-Path '.audit/logs' ($taskCase.Name + '.log')
        & $Godot @taskArguments *> $taskLog
        if ($LASTEXITCODE -ne 0 -or (Select-String -LiteralPath $taskLog -Pattern 'SCRIPT ERROR:|Parse Error:|^ERROR:')) {
            throw "$($taskCase.Name) failed; see $taskLog"
        }
        Write-Output "$($taskCase.Name): completed; $taskLog"
    }
    $taskGeneratedImports = @(& git diff --name-only -- '*.import')
    $taskRestoreImports = @($taskGeneratedImports | Where-Object { $_ -notin $taskOriginalImports })
    if ($taskRestoreImports.Count -gt 0) {
        & git restore --worktree -- $taskRestoreImports
        if ($LASTEXITCODE -ne 0) { throw 'Could not restore audit-generated .import sidecars' }
        Write-Output "restored $($taskRestoreImports.Count) audit-generated import sidecar(s)"
    }
    $env:APPDATA = $taskPreviousAppData
    & $Python tools/check_glyphs.py
    if ($LASTEXITCODE -ne 0) { throw 'Glyph check failed (requires fonttools)' }
    node tests/web_shell_test.mjs
    if ($LASTEXITCODE -ne 0) { throw 'Web loader check failed' }
    if ($ExportWeb) {
        & $Godot --headless --path . --export-release Web .audit/web/index.html *> .audit/logs/export.log
        if ($LASTEXITCODE -ne 0 -or (Select-String .audit/logs/export.log -Pattern 'SCRIPT ERROR:|Parse Error:|^ERROR:')) { throw 'Web export failed' }
        & $Python tools/patch_web_shell.py .audit/web/index.html
        if ($LASTEXITCODE -ne 0) { throw 'Web patch failed' }
        $taskFirstHash = (Get-FileHash .audit/web/index.html).Hash
        & $Python tools/patch_web_shell.py .audit/web/index.html
        if ($LASTEXITCODE -ne 0 -or $taskFirstHash -ne (Get-FileHash .audit/web/index.html).Hash) { throw 'Web patch is not idempotent' }
        node tests/web_shell_test.mjs .audit/web/index.html
        if ($LASTEXITCODE -ne 0) { throw 'Exported loader check failed' }
    }
    Write-Output 'Audit execution completed. Read diagnostic observations; this does not certify production readiness.'
} finally {
    $env:APPDATA = $taskPreviousAppData
    Set-Location -LiteralPath $taskPreviousDirectory
}
